<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>0.1.0</Version>
    <Authors>varma02@github</Authors>
    <Product>Hopparr CLI</Product>
    <Description>A command line interface for the Hopparr media manager</Description>
    <PackageTags>hopparr;cli;commandline;media</PackageTags>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
